name: Git Credentials
description: Git Credentials

inputs:
  HOMEBREW_GITHUB_API_TOKEN:
    description: "Homebrew GitHub API Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: Configure git credentials
      shell: bash
      run: |
        git config --global user.name "Brewforge-Bot"
        git config --global user.email "brewforge-bot@aliyun.com"
        git config --global url."https://x-access-token:${{ inputs.HOMEBREW_GITHUB_API_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: show git context
      shell: bash -ieo pipefail {0}
      run: |
        cat $HOME/.gitconfig
        cat $GITHUB_ENV
