name: Reproducible Bug Report
description: If you’re sure it’s reproducible and not just your machine, submit an issue so we can investigate
labels: bug
body:
  - type: checkboxes
    attributes:
      label: Verification
      description: Please verify that you’ve followed these steps
      options:
        - label: I have retried my command with `--force`.
          required: false
        - label: I ran `brew update-reset && brew update` and retried my command.
          required: false
        - label: I ran `brew doctor`, fixed as many issues as possible and retried my command.
          required: false
  - type: textarea
    attributes:
      label: Description of issue
    validations:
      required: true
  - type: input
    attributes:
      label: Command that failed
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output of command with `--verbose --debug`
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output of `brew doctor` and `brew config`
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output of `brew tap`
      render: shell
    validations:
      required: true
